import { notFound } from "next/navigation";
import { db } from "@/server/db";
import { renderMarkdown } from "@/lib/utils/markdown";
import { Sparkles } from "lucide-react";

export const dynamic = "force-dynamic";

type ToolCallSnapshot = {
  id: string;
  name: string;
  input?: unknown;
  ok?: boolean;
  output?: unknown;
};

export default async function SharedConversationPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const share = await db.agentConversationShare.findUnique({
    where: { slug },
    include: {
      conversation: {
        include: {
          workspace: { select: { name: true, clientName: true } },
          messages: { orderBy: { ordinal: "asc" } },
        },
      },
    },
  });

  if (!share || share.revoked) notFound();
  if (share.expiresAt && share.expiresAt.getTime() < Date.now()) {
    return (
      <ShareLayout title="Link expired" subtitle={null}>
        <p className="text-sm text-muted-foreground text-center py-12">
          This shared transcript has expired. Ask the original author for a
          fresh link.
        </p>
      </ShareLayout>
    );
  }

  const workspaceLabel =
    share.conversation.workspace.clientName?.trim() ||
    share.conversation.workspace.name;
  const title = share.title ?? share.conversation.title;

  return (
    <ShareLayout
      title={title}
      subtitle={`${workspaceLabel} · Shared ${share.createdAt.toLocaleDateString()}`}
    >
      <div className="space-y-6">
        {share.conversation.messages.map((m) => {
          if (m.role === "user") {
            return (
              <div key={m.id} className="flex justify-end">
                <div className="max-w-[85%] rounded-2xl rounded-br-md bg-primary text-white px-4 py-2.5 text-[15px]">
                  {m.content}
                </div>
              </div>
            );
          }

          const toolCalls = !share.redactToolCalls && Array.isArray(m.toolCalls)
            ? (m.toolCalls as ToolCallSnapshot[])
            : [];

          return (
            <div key={m.id} className="space-y-2">
              {toolCalls.map((c) => (
                <div
                  key={c.id}
                  className="inline-flex items-center gap-1.5 text-[11px] rounded-lg border border-[var(--ai)]/30 bg-[var(--ai)]/5 px-2.5 py-1 font-mono text-[var(--ai)]"
                >
                  {c.name}
                  {c.ok === false && (
                    <span className="text-red-600">✗</span>
                  )}
                </div>
              ))}
              <div className="rounded-2xl rounded-bl-md bg-card border px-4 py-2.5 text-[15px] leading-relaxed prose-sm">
                {renderMarkdown(m.content)}
              </div>
            </div>
          );
        })}
      </div>
    </ShareLayout>
  );
}

function ShareLayout({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle: string | null;
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b bg-gradient-to-r from-[var(--ai)]/5 to-transparent">
        <div className="max-w-3xl mx-auto px-5 py-6">
          <div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-wider text-[var(--ai)]/80">
            <Sparkles className="h-3.5 w-3.5" />
            Shared agent transcript
          </div>
          <h1 className="mt-1 text-2xl font-bold text-foreground">{title}</h1>
          {subtitle && (
            <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>
          )}
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 py-8">{children}</main>

      <footer className="max-w-3xl mx-auto px-5 py-8 text-center text-[11px] text-muted-foreground">
        Generated by EAM ·{" "}
        <a
          href="https://eampoc.vercel.app"
          className="hover:text-[var(--ai)] transition-colors"
        >
          eampoc.vercel.app
        </a>
      </footer>
    </div>
  );
}
